### PR TITLE
Add imag/real wrappers.

### PR DESCRIPTION
**Pull request by dopplershift**
The main part of this PR is to add `real` and `imag` wrappers, that check and apply proper units. I've also included a fix to the `quantitizer` decorator, which was mistakenly adding a call to `simplified`.

### CODE REVIEW

**Comment by burnpanck** [comment]
Note that your fix of the `out` parameter is flawed: While the returned Quantity will indeed share data with the array passed to `out`, if the units of the value passed to `out` are off, it will actually hold wrong values. Thus, if the `out` parameter is used just to avoid the memory allocation, then your fix is fine; If you actually want the data to be placed in that array, your fix fails silently.
See my PR #87, which fixes both the *out* and *axis* parameters more thoroughly.

**Comment by ddale** [comment]
Sorry for neglecting quantities for so long. If you can incorporate @burnpanck's fix, and add a unit test, I will merge.

**Comment by dopplershift** [comment]
Ok, well two of the commits (adding squeeze and fixing some wrapped methods) are no longer needed. I've updated the PR to reflect what's left. I'll also add tests for what I'm proposing.

**Comment by dopplershift** [comment]
Done. I didn't add tests for `quantitizer` because I'm not really sure how to start (and I don't remember what I was doing when I hit the problems.) The fix is trivially correct, though.

**Pull request merged**
