### PR TITLE
Preserve dtype in rescale

### PR DESCRIPTION
**Pull request by bjodah**
There are also some lines in `def astype` which look suspicious, (dtype is not propagated), but I have yet to come up with a small test for those. But I think this changeset is sensible on its own.

### CODE REVIEW

**Comment by bjodah** [comment]
I managed to come up with a test and a fix for the silent conversion of dtype between UncertainQuantity and Quantity.

I haven't yet had time to look into the test failures.

**Comment by bjodah** [comment]
Alright, I managed to keep backwards compatibility by setting `dtype='d'` for `put` and `__setitem__`. I think this is ready for review.

**Comment by bjodah** [comment]
I tested this branch with my downstream projects, that uncovered another bug which is now fixed. But perhaps this branch should be tested against some other code base before merge, just to be on the safe side.

**Comment by apdavison** [comment]
Hi @bjodah,
I'm missing some context with this PR. Please can you give an example of what the current master branch does wrong, and how this PR fixes it? And please could you also add this example as a unit test?

**Comment by bjodah** [comment]
Hi @apdavison,

Sure. The background is that I sometimes work with arrays where I mix floating point numbers and symbolic objects from SymPy. The arrays containing symbols from SymPy have the dtype "object" and they cannot (naturally) be converted to e.g. float64, something that currently happens in the master branch of quantities (causing exceptions to be raised even on basic operations).

So dug into the dtype handling of `quantities` and found a number of (what I think are) inconsistencies, so I designed test cases for those (see the added tests in this PR) and patched the handling of `dtype` throughout `quantities`. The tests I added cover the issues I experienced with working with SymPy's `Symbol` class, but since I did not want to add `SymPy` as a dependency of the test suite, I simply used other floating point `dtypes` to track conversions in `quantities`.

And then I also added `numpy.exp2` to functions handled by quantities since I ran into an issue where it was missing for me.

**Comment by bjodah** [comment]
I hope I don't bother you with a friendly ping @apdavison, I was just wondering if you have had a chance to look at this PR again? I've been using this branch quite extensively now, and I feel pretty confident that this PR does the right thing™.

**Comment by apdavison** [comment]
Hi @bjodah, pings are always welcome.

**Pull request merged**
