### PR TITLE
Updated README and travis script

### PR DESCRIPTION
**Pull request by bjodah**
This is a minor PR for updating the README and travis test script.

Changes to travis script:

- Also test for Python 3.4
- Change tested version of `numpy` from v1.7.0 to:
    - v1.7.1
    - v1.9.1

To see what the proposed README.rst renders like, see:
https://github.com/bjodah/python-quantities/tree/update_readme_travis

### CODE REVIEW

**Comment by tbekolay** [comment]
Looks great to me!

**Comment by bjodah** [comment]
Glad to hear. Should we add a gitter channel as well? https://gitter.im
It's practically zero-work to do so. It sort of works like a non-threaded mailing list and might be helpful for users who has questions. I would try to be available there in that case.

**Comment by tbekolay** [comment]
I've never used gitter before, but it seems like a useful tool. I don't have full permissions so I can't add a webhook, but I made a room at https://gitter.im/python-quantities .

**Comment by ddale** [comment]
Let's discuss gitter in a separate issue.

**Comment by ddale** [comment]
Thank you very much for this contribution!

**Pull request merged**
