### PR TITLE
Updates to the documentation

### PR DESCRIPTION
**Pull request by apdavison**
in preparation for a possible 0.12.0 release

### CODE REVIEW

**Comment by apdavison** [comment]
@ddale I think this would be a good time to make a new release (0.12.0), since it has been 18 months since the last release, and the current master branch fixes a number of things that are broken when using the 0.11.1 release with NumPy 1.13.

I would be happy to make the release if you are short of time. If you're ok with this, please could you add me as a maintainer on PyPI and readthedocs? My username on both services is the same as my Github username.

**Comment by apdavison** [comment]
@ddale any thoughts?

**Comment by ddale** [comment]
@apdavison sounds great, I'll work on adding you at PyPI and RTD

**Comment by ddale** [comment]
@apdavison your should be a maintainer at both sites now, please let me know if you don't.

Also, welcome aboard and thank you!

**Comment by apdavison** [comment]
@ddale Thanks! Everything seems to work. I've pushed a new release - 0.12.0 - to PyPI. The docs are currently building at RTD. Many thanks for your confidence.

**Pull request merged**
