### PR TITLE
Avoid invalid esc seq in re.sub template (fixes gh-148)

### PR DESCRIPTION
**Pull request by bjodah**
- Fixes https://github.com/python-quantities/python-quantities/issues/148

### CODE REVIEW

**Comment by bjodah** [comment]
cc @apdavison, would you mind reviewing?

**Comment by bjodah** [comment]
I see. No problem, what "sparisty mask" would you suggest?

**Comment by apdavison** [comment]
Probably the easiest thing is to keep the existing, dense matrix but add exclusions for Python 3.7

**Comment by bjodah** [comment]
should I add all Numpy versions inbetween? (I'd say no)

**Comment by apdavison** [comment]
I think for each minor version we should test with only the latest patch release. (This means we should probably update to testing with NumPy 1.13.3)

**Comment by bjodah** [comment]
This is what I come up with (looking at tags over at numpy/numpy):
    - NUMPY_VERSION="1.8.2"
    - NUMPY_VERSION="1.9.3"
    - NUMPY_VERSION="1.10.4"
    - NUMPY_VERSION="1.11.3"
    - NUMPY_VERSION="1.12.1"
    - NUMPY_VERSION="1.13.3"
    - NUMPY_VERSION="1.14.5"

i.e. 7 * 4 + 1 = 29 combinations

**Comment by apdavison** [comment]
Yeah, that's starting to get unwieldy, but the test suite runs fairly quickly, so I think it's ok for now.

**Comment by sanjayankur31** [comment]
@apdavison - any chance of a minor release now that this fix is in? It'll save us downstream distribution package maintainers from having to carry a patch. :)

**Comment by apdavison** [comment]
@sanjayankur31 Done

**Comment by apdavison** [comment]
and @bjodah : many thanks for the fix!

**Pull request merged**
