### PR TITLE
More ufuncs (fixes #76)

### LINKED ISSUE #76: isclose, allclose and less_equal ufunc not supported
FYI - bummer.

        2188     array([True, False])
        2189     >>> np.isclose([1.0, np.nan], [1.0, np.nan], equal_nan=True)
        2190     array([True, True])
        2191     """
        2192     def within_tol(x, y, atol, rtol):
     -> 2193         with errstate(invalid='ignore'):
        2194             result = less_equal(abs(x-y), atol + rtol * abs(y))
        2195         if isscalar(a) and isscalar(b):
        2196             result = bool(result)
        2197         return result
        2198
    *** ValueError: ufunc %r not supported by quantities
                    please file a bug report at https://github.com/python-quantities

### PR DESCRIPTION
**Pull request by bjodah**
The goal is to support:

- [np.equal](http://docs.scipy.org/doc/numpy/reference/generated/numpy.equal.html)
- [np.not_equal](http://docs.scipy.org/doc/numpy/reference/generated/numpy.not_equal.html)
- [np.less](http://docs.scipy.org/doc/numpy/reference/generated/numpy.less.html)
- [np.less_equal](http://docs.scipy.org/doc/numpy/reference/generated/numpy.less_equal.html)
- [np.greater](http://docs.scipy.org/doc/numpy/reference/generated/numpy.greater.html)
- [np.greater_equal](http://docs.scipy.org/doc/numpy/reference/generated/numpy.greater_equal.html)

### CODE REVIEW

**Comment by ddale** [comment]
Looks like there are merge conflicts, would you mind having a look?

**Comment by bjodah** [comment]
I'll rebase this once more when tests for the master branch is passing.

**Comment by bjodah** [comment]
Since the code base already assumes NumPy 1.8+:
https://github.com/python-quantities/python-quantities/blob/master/quantities/quantity.py#L617
http://docs.scipy.org/doc/numpy-1.9.3/reference/generated/numpy.nanmean.html#numpy.nanmean

I bumped the travis version to 1.8.2.

**Comment by bjodah** [comment]
This is ready for review.

**Comment by ddale** [comment]
Looks great, thanks!

**Pull request merged**
