### PR TITLE
Increase CI test space

### PR DESCRIPTION
**Pull request by thisch**
Test python-quantities with more numpy versions.

### CODE REVIEW

**Comment by thisch** [comment]
Do you think it is okay if we require a newer minimum numpy version in cpython 3.7 than what is supported for older cpython versions? Then almost all tests would pass. In the last CI job there was also a timeout error of a cpython 3.4 run, which is unrelated to this PR.

**Comment by apdavison** [comment]
yes, I would say that is fine.

**Comment by thisch** [comment]
@apdavison tests pass now. Anything else you want to be part of this PR or can we merge it?

**Comment by apdavison** [comment]
Merged. Many thanks @thisch

**Pull request merged**
