### PR TITLE
Implemented preferred rescaling

### PR DESCRIPTION
**Pull request by rgerkin**
See #172.

### CODE REVIEW

**Comment by apdavison** [comment]
Hi Rick, this seems like a useful feature, and the implementation seems reasonable although I wonder if there isn't a more robust method of comparing units than by their string representation.

Please could you

- add a couple of tests
- add the usage examples to the docs, rather than adding a new demo folder (which risks making the project more difficult to maintain)
- revert the "versioneer" commit, which is unrelated to the topic of the PR


(by the way, what is the problem you're seeing with versioneer? - it was working fine last time I made a release)

**Comment by rgerkin** [comment]
Yes, I will do all those things.  Sorry about the versioneer thing.  There was a period several months ago when it was not working, but it's been resolved so I will rebase and remove that commit.

**Comment by rgerkin** [comment]
I've simplified the PR as requested, and added unit tests.  But I'm unclear as to where the usage examples would go, or if they should go anywhere at all.  

As for the string comparison, I could probably replace that with a direct comparison of the simplified units, but I am always hesitant to trust `__eq__` based on previous experiences.  But if you think that is better I'll make the change.

**Comment by rgerkin** [comment]
@apdavison Any thoughts?

**Comment by apdavison** [comment]
Hi @rgerkin, this looks good. The documentation is auto-generated, so the best place for the usage examples would be in docstrings. Please could you add a docstring for `rescale_preferred` and extend the docstring for `rescale` to explain what happens if `units` is `None`?

**Comment by rgerkin** [comment]
@apdavison OK, let me know how that looks (1a0dc15).

**Pull request merged**
